# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payroll_type', models.CharField(choices=[('F', 'Full-Time'), ('P', 'Part-time'), ('S', 'Salary')], default='F', max_length=1)),
                ('pay_rate', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('O', 'Ongoing'), ('T', 'Temporary')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Address', verbose_name='Related address')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Employee', verbose_name='Related account')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Employee', verbose_name='Related account')),
                ('pay_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PayDetails', verbose_name='Related pay_details')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave', models.IntegerField()),
                ('sick_leave', models.IntegerField()),
                ('service_leave', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_pay_date', models.DateField()),
                ('end_pay_date', models.DateField()),
                ('hours', models.FloatField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='default', max_length=10)),
                ('role_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Roles'),
        ),
    ]
