# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('itemID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
