# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_qty', models.FloatField(blank=True, null=True)),
                ('reserved_qty', models.FloatField(blank=True, null=True)),
                ('ordered_qty', models.FloatField(blank=True, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
            ],
        ),
    ]
