# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170821_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ordered_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
