# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20171002_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ordered_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
