# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('item_desc', models.CharField(max_length=120, verbose_name='Description')),
                ('units', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
            ],
        ),
    ]
