# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemAttributes',
            new_name='ItemAttribute',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemDescription',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='productCategory',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='itemattribute',
            old_name='itemId',
            new_name='item_id',
        ),
    ]
