# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('account_number', models.CharField(max_length=10, primary_key=1, serialize=False)),
                ('business_number', models.CharField(max_length=20)),
                ('party_name', models.CharField(max_length=100)),
                ('party_type', models.CharField(choices=[('C', 'Customer'), ('V', 'Vendor')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party', verbose_name='Related account')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Address', verbose_name='Related address')),
            ],
        ),
    ]
