# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('suburb', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(default='Australia', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('bsb_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('str_value', models.CharField(max_length=150)),
            ],
        ),
    ]
