# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170827_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('str_value', models.CharField(max_length=150)),
            ],
        ),
    ]
