# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountAttributeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=30)),
                ('dimension_1', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_2', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_3', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_4', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_5', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_6', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_7', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_8', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountAttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('apply_type', models.CharField(choices=[('Add', 'Add to price'), ('Apply', 'Apply to price')], max_length=1)),
                ('product_attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DiscountAttributeTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('account_number', models.CharField(max_length=8)),
                ('order_type', models.CharField(choices=[('S', 'Sale'), ('P', 'Purchase')], max_length=1)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('C', 'Created'), ('O', 'Ordered'), ('D', 'Delivered'), ('I', 'Invoiced')], max_length=1)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_line_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeDimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=30)),
                ('dim', models.CharField(choices=[('Dim1', 'Dimension 1'), ('Dim2', 'Dimension 2'), ('Dim3', 'Dimension 3'), ('Dim4', 'Dimension 4'), ('Dim5', 'Dimension 5'), ('Dim6', 'Dimension 6'), ('Dim7', 'Dimension 7'), ('Dim8', 'Dimension 8')], max_length=1)),
                ('required', models.BooleanField()),
            ],
        ),
    ]
