# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountAttributeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=30)),
                ('dimension1', models.CharField(max_length=50)),
                ('dimension2', models.CharField(max_length=50)),
                ('dimension3', models.CharField(max_length=50)),
                ('dimension4', models.CharField(max_length=50)),
                ('dimension5', models.CharField(max_length=50)),
                ('dimension6', models.CharField(max_length=50)),
                ('dimension7', models.CharField(max_length=50)),
                ('dimension8', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountAttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('applyType', models.CharField(choices=[('Add', 'Add to price'), ('Apply', 'Apply to price')], max_length=1)),
                ('productAttributeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DiscountAttributeTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.IntegerField()),
                ('AccountNumber', models.CharField(max_length=8)),
                ('OrderType', models.CharField(choices=[('S', 'Sale'), ('P', 'Purchase')], max_length=1)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('DeliveryDate', models.DateTimeField()),
                ('OrderStatus', models.CharField(choices=[('Created', 'Created'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Invoiced', 'Invoiced')], max_length=1)),
                ('InvoiceDate', models.DateTimeField()),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderLineId', models.IntegerField()),
                ('ItemId', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('DiscountPrice', models.FloatField()),
                ('Unit', models.CharField(max_length=10)),
                ('OrderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeDimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCategory', models.CharField(max_length=30)),
                ('dim', models.CharField(choices=[('Dim1', 'Dimension 1'), ('Dim2', 'Dimension 2'), ('Dim3', 'Dimension 3'), ('Dim4', 'Dimension 4'), ('Dim5', 'Dimension 5'), ('Dim6', 'Dimension 6'), ('Dim7', 'Dimension 7'), ('Dim8', 'Dimension 8')], max_length=1)),
                ('required', models.BooleanField()),
            ],
        ),
    ]
