# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170821_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discountattributetypes',
            name='dimension_8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('C', 'Created'), ('O', 'Ordered'), ('D', 'Delivered'), ('I', 'Invoiced')], max_length=1),
        ),
    ]
